num1 = int(input("输入A的成绩："))
num2 = int(input("输入B的成绩："))
num3 = int(input("输入C的成绩："))
num4 = int(input("输入D的成绩："))
num5 = int(input("输入E的成绩："))
print("最高分是:",max(num1,num2,num3,num4,num5))
print("最低分是：",min(num1,num2,num3,num4,num5))
print("平均分是：",(num1+num2+num3+num4+num5)/5)
print("总分是：",num1+num2+num3+num4+num5)
